- hosts: two
  user:  nimra.bashir
  become: true
  vars: 
     usr_nm: [muhammad.faisal, muhammad.asghar, ehtesham.ahmed]
  tasks:
     - name: user check if exist
       shell: getent passwd {{ item }} | wc -l
       loop: "{{ usr_nm }}"
       register: list_user  
     - name: create user if not exist
       user:
        name: "{{ item[0] }}"
        password: "{{ 'P@kistan@123/?' | password_hash('sha512') }}"
       when: '{{ item[1].stdout == "0" }}'
       with_together:
         - "{{ usr_nm }}"
         - "{{ list_user.results }}"
       register: outp
     - debug:
        var: outp 
     - name: add user to wheel group
       user:
         name: "{{ item }}"
         groups: wheel
         append: yes
       loop: "{{ usr_nm }}"
     - name: force user to change password at first login
       shell: chage --lastday 0 {{ item }}
       loop: "{{ usr_nm }}"
       register: op
     - debug:
        var: op
        #     - name: Allow the user to run any commands as sudo
        #community.general.sudoers:
        #name: sudo user
        #state: present
        #nopassword: no
        #user: "{{ item }}"
        #commands: ALL
        #loop: "{{ usr_nm }}"
        #register: sudo
        #- debug: 
        # var: sudo
